apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image-registry
  labels:
    app: tekton-workshop
spec:
  type: image
  params:
  - name: url
    value: docker.io/kamlesh1/tkp-pipeline-demo:tekton
