apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-repo
spec:
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/kamleshjec/tekton-pipeline.git
  type: git
